import 'dart:typed_data';

import 'package:flutter/foundation.dart' show kIsWeb;

import '../ffi/native_bridge.dart';

/// High-level content encryption/decryption with mandatory memory zeroing.
///
/// ## Design philosophy:
///
/// Unencrypted content must NEVER exist on disk. The lifecycle is:
/// ```
/// Server → encrypted bytes → decrypt in memory → render to GPU → zero buffer
/// ```
///
/// ## Why memory zeroing matters:
///
/// After content is rendered, the decrypted bytes linger in RAM. An attacker
/// with a memory dump (Frida, GameGuardian, or a jailbroken device) can search
/// for image/video signatures and extract the content. By explicitly zeroing
/// the buffer, we reduce the window of exposure to the absolute minimum.
///
/// ## Chunk-based streaming:
///
/// Large files (videos, PDFs) should NOT be decrypted all at once.
/// Instead, the caller decrypts chunks, renders each, then zeros it.
/// This means at most one chunk of unencrypted data exists in memory
/// at any time. [decryptChunk] supports this pattern.
///
/// ## Thread safety:
///
/// All Rust FFI calls are stateless and thread-safe. The Rust functions
/// do not hold any global state. Multiple encryptions/decryptions can
/// run concurrently (e.g., via `compute()`).
class ContentEncryptor {
  ContentEncryptor._();

  static final ContentEncryptor instance = ContentEncryptor._();

  /// Whether the native encryption library is available.
  ///
  /// False on web (uses WASM in future) and unsupported platforms.
  bool get isAvailable => !kIsWeb && NativeBridge.isAvailable;

  // ─── Key Management ───

  /// Generate a new content encryption key (AES-256 = 32 bytes).
  ///
  /// Uses the OS cryptographic random number generator via Rust.
  /// The key should be stored securely (see [SecureKeyStorage]).
  Uint8List generateKey() {
    _assertAvailable();
    return NativeBridge.instance.generateKey();
  }

  /// Encryption overhead in bytes (nonce 12 + auth tag 16 = 28).
  ///
  /// Encrypted data = plaintext + overhead.
  /// The caller needs this to allocate the right buffer size.
  int get overhead {
    _assertAvailable();
    return NativeBridge.instance.encryptionOverhead;
  }

  // ─── Encryption ───

  /// Encrypt content bytes with AES-256-GCM.
  ///
  /// Returns: nonce (12B) + ciphertext + auth tag (16B).
  /// Returns null if encryption fails.
  ///
  /// The output is authenticated — any modification (even a single bit
  /// flip) will cause [decryptContent] to return null.
  Uint8List? encryptContent(Uint8List key, Uint8List plaintext) {
    _assertAvailable();
    return NativeBridge.instance.encrypt(key, plaintext);
  }

  // ─── Decryption ───

  /// Decrypt content bytes with AES-256-GCM.
  ///
  /// Returns the original plaintext, or null if:
  /// - Authentication tag mismatch (data was tampered with)
  /// - Wrong key
  /// - Malformed input
  ///
  /// **IMPORTANT:** The caller MUST call [zeroBuffer] on the returned
  /// Uint8List after rendering. Failing to do so leaves decrypted content
  /// in RAM where it can be extracted by memory inspection tools.
  Uint8List? decryptContent(Uint8List key, Uint8List encrypted) {
    _assertAvailable();
    return NativeBridge.instance.decrypt(key, encrypted);
  }

  /// Decrypt a single chunk of a streamed content file.
  ///
  /// ## Streaming decryption pattern:
  ///
  /// Each chunk is independently encrypted with the same key but a unique
  /// nonce (generated by [encryptContent]). This means:
  /// - Chunks can be decrypted independently (random access)
  /// - Corrupted/tampered chunks fail individually without breaking others
  /// - Only one decrypted chunk exists in memory at a time
  ///
  /// Usage:
  /// ```dart
  /// for (final chunk in encryptedChunks) {
  ///   final decrypted = encryptor.decryptChunk(key, chunk);
  ///   if (decrypted == null) throw IntegrityException();
  ///   await renderToGPU(decrypted);
  ///   encryptor.zeroBuffer(decrypted);  // MANDATORY
  /// }
  /// ```
  Uint8List? decryptChunk(Uint8List key, Uint8List encryptedChunk) {
    return decryptContent(key, encryptedChunk);
  }

  // ─── Memory Zeroing ───

  /// Overwrite a buffer with zeros to prevent memory extraction.
  ///
  /// ## Why this is critical:
  ///
  /// After decrypted content is rendered, the Uint8List still holds the
  /// plaintext bytes in the Dart heap. On a compromised device:
  /// - Frida can scan process memory for image headers (JPEG FFD8, PNG 89504E47)
  /// - GameGuardian can dump the entire heap
  /// - A jailbroken device can read /proc/{pid}/mem
  ///
  /// By zeroing the buffer immediately after use, we reduce the exposure
  /// window from "until garbage collection" to "rendering duration only".
  ///
  /// ## Dart GC caveat:
  /// Dart's garbage collector may have already copied the data to a different
  /// memory location (generational GC promotes objects). We can't guarantee
  /// ALL copies are zeroed, but zeroing the known reference is still valuable
  /// as defense-in-depth.
  void zeroBuffer(Uint8List buffer) {
    buffer.fillRange(0, buffer.length, 0);
  }

  /// Zero multiple buffers at once (convenience for cleanup blocks).
  void zeroBuffers(List<Uint8List> buffers) {
    for (final buffer in buffers) {
      buffer.fillRange(0, buffer.length, 0);
    }
  }

  // ─── Content Integrity ───

  /// Compute a checksum of content for integrity verification.
  ///
  /// Uses FNV-1a hash (fast, non-cryptographic).
  /// Used to verify content hasn't been modified in transit.
  int computeChecksum(Uint8List data) {
    _assertAvailable();
    return NativeBridge.instance.computeChecksum(data);
  }

  /// Verify content integrity against a known checksum.
  bool verifyChecksum(Uint8List data, int expected) {
    _assertAvailable();
    return NativeBridge.instance.verifyChecksum(data, expected);
  }

  // ─── Private ───

  void _assertAvailable() {
    assert(isAvailable, 'ContentEncryptor: Native encryption not available');
  }
}
