// Auto-generated by cbindgen. Do not edit.

#ifndef CYBERGUARD_CORE_H
#define CYBERGUARD_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Overhead added by encryption: nonce + tag.
 */
#define ENCRYPTION_OVERHEAD 28

/**
 * Encode a steganographic watermark into RGBA pixel data.
 *
 * # Safety
 * - `pixels` must point to a valid buffer of at least `pixel_count * 4` bytes
 * - `user_id` must point to exactly 32 bytes
 * - `session_id` must point to exactly 12 bytes
 */
int32_t cg_watermark_encode(uint8_t *pixels,
                            uint32_t pixel_count,
                            const uint8_t *user_id,
                            uint64_t timestamp_ms,
                            const uint8_t *session_id);

/**
 * Decode a steganographic watermark from RGBA pixel data.
 *
 * # Safety
 * - `pixels` must point to a valid buffer of at least `pixel_count * 4` bytes
 * - `user_id_out` must point to a writable buffer of at least 32 bytes
 * - `timestamp_ms_out` must point to a valid u64
 * - `session_id_out` must point to a writable buffer of at least 12 bytes
 */
int32_t cg_watermark_decode(const uint8_t *pixels,
                            uint32_t pixel_count,
                            uint8_t *user_id_out,
                            uint64_t *timestamp_ms_out,
                            uint8_t *session_id_out);

/**
 * Get the minimum number of pixels required for watermark encoding.
 */
uint32_t cg_watermark_min_pixels(void);

/**
 * Encrypt data using AES-256-GCM.
 *
 * # Safety
 * - `key` must point to exactly 32 bytes
 * - `plaintext` must point to `plaintext_len` bytes
 * - `output` must point to a writable buffer of at least `plaintext_len + 28` bytes
 *
 * # Returns
 * Number of bytes written to output (positive), or negative error code.
 */
int32_t cg_encrypt(const uint8_t *key,
                   const uint8_t *plaintext,
                   uint32_t plaintext_len,
                   uint8_t *output,
                   uint32_t output_capacity);

/**
 * Decrypt data using AES-256-GCM.
 *
 * # Safety
 * - `key` must point to exactly 32 bytes
 * - `encrypted` must point to `encrypted_len` bytes
 * - `output` must point to a writable buffer of at least `encrypted_len - 28` bytes
 *
 * # Returns
 * Number of plaintext bytes written (positive), or negative error code.
 */
int32_t cg_decrypt(const uint8_t *key,
                   const uint8_t *encrypted,
                   uint32_t encrypted_len,
                   uint8_t *output,
                   uint32_t output_capacity);

/**
 * Generate a cryptographically secure random 256-bit key.
 *
 * # Safety
 * - `key_out` must point to a writable buffer of exactly 32 bytes
 */
int32_t cg_generate_key(uint8_t *key_out);

/**
 * Get the encryption overhead in bytes (nonce + auth tag).
 */
uint32_t cg_encryption_overhead(void);

/**
 * Check if a process name matches a known screen capture tool.
 *
 * # Safety
 * - `process_name` must be a valid null-terminated C string
 *
 * # Returns
 * 1 if the process is a known capture tool, 0 if not.
 */
int32_t cg_is_capture_process(const char *process_name);

/**
 * Check if a string contains hooking framework signatures.
 *
 * # Safety
 * - `target` must be a valid null-terminated C string
 *
 * # Returns
 * 1 if a hook signature is found, 0 if not.
 */
int32_t cg_is_hook_signature(const char *target);

/**
 * Compute a FNV-1a checksum over a memory region.
 *
 * # Safety
 * - `data` must point to at least `len` bytes
 */
uint64_t cg_compute_checksum(const uint8_t *data, uint32_t len);

/**
 * Verify a memory region's checksum.
 *
 * # Safety
 * - `data` must point to at least `len` bytes
 *
 * # Returns
 * 1 if checksum matches (integrity OK), 0 if mismatch (tampered).
 */
int32_t cg_verify_checksum(const uint8_t *data, uint32_t len, uint64_t expected);

/**
 * Free a string allocated by Rust.
 *
 * # Safety
 * - `ptr` must be a string previously returned by a `cg_*` function,
 *   or null (which is a no-op).
 */
void cg_free_string(char *ptr);

/**
 * Get the library version string.
 *
 * # Returns
 * A null-terminated string. Caller must NOT free this pointer
 * (it points to a static string).
 */
const char *cg_version(void);

#endif  /* CYBERGUARD_CORE_H */
